// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YanLoadingTracker.Models
{
    public class CourseConfiguration : IEntityTypeConfiguration<Course>
    {
        public void Configure(EntityTypeBuilder<Course> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Course_pk")
                .IsClustered(false);

            entity.ToTable("Course");

            entity.HasIndex(e => e.Id)
                .HasName("Course_Id_uindex")
                .IsUnique();

            entity.Property(e => e.CourceName).HasMaxLength(20);

            entity.Property(e => e.CourceNumber)
                .IsRequired()
                .HasMaxLength(1);
        }
    }
}
