// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YanLoadingTracker.Models
{
    public class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Departments_pk")
                .IsClustered(false);

            entity.ToTable("Department");

            entity.HasComment("Кафедры");

            entity.HasIndex(e => e.Id)
                .HasName("Departments_Id_uindex")
                .IsUnique();

            entity.Property(e => e.Name).IsRequired();
        }
    }
}
