// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace YanLoadingTracker.Models
{
    public class OccupationTypeConfiguration : IEntityTypeConfiguration<OccupationType>
    {
        public void Configure(EntityTypeBuilder<OccupationType> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("OccupationTypes_pk")
                .IsClustered(false);

            entity.HasComment("Типы занятий");

            entity.HasIndex(e => e.Id)
                .HasName("OccupationTypes_Id_uindex")
                .IsUnique();

            entity.Property(e => e.Name).IsRequired();
        }
    }
}
