// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace YanLoadingTracker.Models
{
    public partial class Course
    {
        public Course()
        {
            Disciplines = new HashSet<Discipline>();
        }

        public int Id { get; set; }

        [Display(Name = "Номер курса")]
        [Required]
        public string CourceNumber { get; set; }

        [Display(Name = "Название курса")]
        [Required]
        public string CourceName { get; set; }

        public virtual ICollection<Discipline> Disciplines { get; set; }

        public override string ToString() => $"{CourceName}";
    }
}
