// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YanLoadingTracker.Models
{
    public partial class Course
    {
        public Course()
        {
            Disciplines = new HashSet<Discipline>();
        }

        public int Id { get; set; }
        public string CourceNumber { get; set; }
        public string CourceName { get; set; }

        public virtual ICollection<Discipline> Disciplines { get; set; }
    }
}