// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace YanLoadingTracker.Models
{
    public partial class Discipline
    {
        public Discipline()
        {
            Loads = new HashSet<Load>();
        }

        public int Id { get; set; }


        [Display(Name = "Название")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Курс")]
        public int? IdCourse { get; set; }
        [Display(Name = "Курс")]
        public virtual Course IdCourseNavigation { get; set; }
        public virtual ICollection<Load> Loads { get; set; }
    }
}
