// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YanLoadingTracker.Models
{
    public partial class Load
    {
        public int IdTeacher { get; set; }
        public int IdDiscipline { get; set; }
        public int IdType { get; set; }

        public virtual Discipline IdDisciplineNavigation { get; set; }
        public virtual Teacher IdTeacherNavigation { get; set; }
        public virtual OccupationType IdTypeNavigation { get; set; }
    }
}