// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace YanLoadingTracker.Models
{
    public partial class OccupationType
    {
        public OccupationType()
        {
            Loads = new HashSet<Load>();
        }

        public int Id
        {
            get; set;
        }

        [Display(Name="Название")]
        public string Name { get; set; }


        public virtual ICollection<Load> Loads { get; set; }


        public override string ToString() => $"{Name}";
    }
}
