// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>



using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace YanLoadingTracker.Models
{
  public partial class Teacher
  {
    public Teacher() { Loads = new HashSet<Load>(); }

    public int Id { get; set; }

    [Display(Name = "Имя")]
    [Required]
    public string FirstName { get; set; }

    [Display(Name = "Фамилия")]
    [Required]
    public string MiddleName { get; set; }

    [Display(Name = "Отчество")]
    [Required]
    public string LastName { get; set; }

    [Display(Name = "Кафедра")]
    public int IdDepartment { get; set; }

    [Display(Name = "Кафедра")]
    public virtual Department IdDepartmentNavigation { get; set; }

    public virtual ICollection<Load> Loads { get; set; }


    [NotMapped]
    public string FullName => $"{MiddleName} {FirstName?[0]}.{LastName?[0]}."    ;

    public override string ToString() => $"{MiddleName} {FirstName?[0]}.{LastName?[0]}."    ;
  }
}